allow-lan: true
mode: rule
log-level: info
# mixed-port: 7890
# external-controller: 127.0.0.1:9090
proxies:
  - name: 🎶 解锁
    type: http
    server: 192.168.0.20
    port: 5200
  - name: 🎶 测试
    type: http
    server: 127.0.0.1
    port: 5200
    
proxy-groups:
  - name: 🎵 网易云音乐
    type: select
    proxies:
      - 🎶 解锁
      - DIRECT

rule-providers:
  NeteaseMusic:
    type: http
    behavior: classical
    # format: text
    path: ./rules/NeteaseMusic.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml
    interval: 86400

rules:
  # Netease Music Advertising
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  # Netease Music
  - RULE-SET,NeteaseMusic,🎵 网易云音乐

  # Final
  - MATCH,DIRECT
