mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: 🎶 解锁
    type: http
    server: 192.168.0.20
    port: 5201
    tls: true

proxy-groups:
  - name: 🎵 网易云音乐
    type: select
    proxies:
      - 🎶 解锁
      - DIRECT

rule-providers:
  NeteaseMusic:
    type: http
    behavior: classical
    format: text
    path: ./rules/NeteaseMusic.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/NetEaseMusic/NetEaseMusic.list
    interval: 86400

rules:
  # Netease Music Advertising
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  # Netease Music
  - RULE-SET,NeteaseMusic,🎵 网易云音乐

  # Final
  - MATCH,DIRECT
